#
# This file contains configuration flags to customize your site
#

# Sitewide variables - primarily used in the header

site-name: Tech For Good
site-description: DoSomething.org Engineering Blog
site-avatar: /ds-neue/assets/images/logo.svg

# Google Analytics tracking code
google_analytics:

# Used for Sitemap.xml and RSS
url: http://tech.dosomething.org

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Redcarpet does a good job of syntax highlighting
# and has a number of useful features
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: pygments

# Blog post permalinks default to the title (but can be overridden)
permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Use the following plug-ins
gems:
  - jekyll-redirect-from # Instead of 301 of alias redirects
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md